### PR TITLE
Added the options_file setting.

### PR DESCRIPTION
**Pull request by mchamberlain**
A JSON file that contains a map of source file names to lists of options
for that file. This provides similar functionality to options_script,
but without the need to run an external script.

I originally based this on issue #135 with the aim of making it more
general, but I am working on a Sublime Text 2/SublimeClang generator for
CMake where I would like to make use of this.

I realise that the options_script is the favoured way of providing this
functionality, I just feel it makes sense for the plug-in to have a built-in way
(that doesn't rely on external scripts that may or may not be limited to a
certain platform or build system) to get different compile flags/options
per source file.

Example:
{
  "/path/to/source_file1.cpp" :
  [
    "-DTEST1",
    "-DTEST2",
    "-I/some/include/dir1"
  ],
  "/path/to/source_file2.h" :
  [
    "-DTEST3",
    "-DTEST4",
    "-I/some/include/dir2"
  ]
}

### CODE REVIEW

**Comment by mchamberlain** [comment]
My apologies, I just noticed some unit tests are failing. Busy fixing it.

**Comment by quarnster** [comment]
> I just feel it makes sense for the plug-in to have a built-in way
> (that doesn't rely on external scripts that may or may not be limited to a
> certain platform or build system) to get different compile flags/options
> per source file.

Is that your only argument for this? This adds a lot of complexity for such a tiny benefit and I really don't see why you can't have an external program spit out the same information. Like this python script:

``` python
import json
import sys

f = open(sys.argv[1])
data = json.load(f)
f.close()
if sys.argv[2] in data:
    for arg in data[sys.argv[2]]:
        print arg

```

Or you could just create a small c program that does the same if you prefer.

**Comment by mchamberlain** [comment]
I suppose I was approaching this with a bit of tunnel vision, I really was just thinking about how I could solve the per source file options problem coming from something like a CMake generator, where ideally you just want to write a project file(s) that the that target software can load and then everything just works and is self-contained. Just that little bit of extra user-friendliness (which I suppose isn't necessarily such a big deal for programmers).

The only other consideration is that this way the options file is loaded only once, with the options script method it is loaded multiple times, but then again the file would have to be really large for that to become an issue.

I suppose project generators could work around this issue by writing out a python script as part of the generation process, and then just leave it as a user configuration issue to ensure that python is executable/in the path.

**Comment by quarnster** [comment]
FYI, I have a [gist for CMake generated compile_commands.json](https://gist.github.com/3944250), mostly thanks to berenm.

Even if the file was huge and took minutes to load, the script is run in a separate thread and only for new translation units so the only possible impact of loading it multiple times would be that it would take slightly longer before completion and navigation operations are available in a newly opened file (in theory&trade;).

I don't see a compelling enough reason to merge this, but thank you for your effort :)

**Pull request closed without merging**
