### PR TITLE
Fixed warnings when frameworks such as <Foundation/Foundation.h> were imported

### PR DESCRIPTION
**Pull request by Jacob640**
A typo in the default build settings seems to have caused some frameworks to not be recognised by clang as system frameworks (i.e. Foundation.h and Cocoa.h).   This has caused an excessive number of warnings to be emitted when these frameworks are included.   This patch resolves the issue.

### CODE REVIEW

**Comment by quarnster** [comment]
It's not a typo and your proposed change is not a fix, but a breakage.

test.mm:

``` objc
#import <Cocoa/Cocoa.h>
```

```
$ clang -nostdinc -isystem "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/" -I/usr/include -I/usr/local/lib/clang/3.3/include/ test.mm
test.mm:1:9: fatal error: 'Cocoa/Cocoa.h' file not found
#import <Cocoa/Cocoa.h>
        ^
1 error generated.
```

```
$ clang -nostdinc -F "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/" -I/usr/include -I/usr/local/lib/clang/3.3/include/ test.mm
---->8----->8------->8---------------
683 warnings generated.
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     -u command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
23:40 /tmp $ clang -nostdinc -F "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/" -I/usr/include -I/usr/local/lib/clang/3.3/include/ test.mm
```

So I'll decline your change, but as all the warnings go away when "-Wno-deprecated-declarations" is added to the options I'll do that instead.

**Comment by Jacob640** [comment]
clang -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/include/ -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/usr/include/c++/4.2.1 -isystem Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/ -isystem C:\MinGW\lib\gcc\mingw32\4.7.0\include -isystem C:\MinGW\lib\gcc\mingw32\4.7.0\include\c++ -isystem C:\MinGW\lib\gcc\mingw32\4.7.0\include\c++\mingw32 -isystem C:\MinGW\include -isystem /usr/include -isystem /usr/include/c++/\* -Wall test.m

The above command compiles on my system fine perhaps this is a 10.7 vs 10.8 issue.   Are you using standard xcode clang or a standalone version.

When I changed the settings in my version of sublime text it did not impede parsing.  Symbols of the included libraries were properly parsed and when the import mark was commented out they disappeared as expected.

**Comment by Jacob640** [comment]
Sorry to be a pain but when does -nostdinc get used in the plugin anyway?

**Comment by quarnster** [comment]
It's not by default, but -isystem is not a valid command for targeting a different sdk version or IOS. The only reason it "works" for you is that the default path gets used so your -isystem is a nop, but does absolutely nothing for people who want to target a specific SDK or Platform.

**Comment by Jacob640** [comment]
Ok thanks

FYI using -Wno-deprecated-declarations still leaves 8 framework warnings on a 10.7 target (but not when using 10.8 frameworks).   -Wnoshift-overflow option is suggested for all of them but obviously you would receive no warning when using depreciated functions or when a bit-shift overflow is detected.

**Pull request closed without merging**
