### PR TITLE
GoTo Implementation fix. 

### PR DESCRIPTION
**Pull request by meyumer**
Fixes:

1- Now looks into all files in open folders with suitable endings. 
2- Constructor and destructor implementations are also included.

Additional comments:

1- (lines 207-238 in sublimeclang.py)
Currently, the files in all open folders are indexed at every call to the 'GoTo Implementation' function. I admit that this could have been done in a smarter way. May be indexing all files in open folders at the very beginning when the plugin is warming up, and updating the list when only a new folder is open and a new file is added to one of the open folders. However, I aimed for minimum intrusion to your code. I am willing to continue working on making this better. Let me know your thoughts. 

2- (lines 201-204 in sublimeclang.py)
Previously, only methods and function declarations were working, now I added the constructor and destructor definitions.

### CODE REVIEW

**Comment by meyumer** [comment]
How about this? search starts from the files in the same folder with the same named files in the same folder, as in your previous implementation. Then continues the search with files in open folders. May be there is a quick way of making this search optional?

**Comment by quarnster** [comment]
@gunayorbay, If you want ctags functionality, why not just use the [ctags plugin](https://github.com/SublimeText/CTags)?

@meyumer, I'm against anything that has a worst case scenario (ie, there is no implementation to be found) of using clang to parse every single .c, .cpp, etc file in a project, especially when that operation blocks the main thread. I'm not a fan of the current implementation blocking the main thread either, even though it's most likely only scanning through a single file.

But having to parse every file is like kicking off a build. Maybe it'll work for smaller projects but some of the projects I'm involved with have a build time of more than 30 minutes and since it's done in the main thread you wont be able to use ST2 at all during that time. It'd be much faster to just do a regular "find in files" searching for the implementation you want at that point.

Here's what I'd ideally like:

1) Keep the same directory same name check as a quick path.
2) If such a file doesn't exist, check if there's a file open already with a filename that matches the header
3) If that also fails, do the following work in a separate thread:
4) Use a priority queue with filenames matching the header name being pushed on top
5) Use a regex search inside of the files to eliminate having to parse files with clang that obviously do not contain the implementation
6) Only files that pass the regex search are then passed on to clang for parsing
7) Make it possible to cancel this scan operation.

**Comment by meyumer** [comment]
@quarnster 
I can see what you have explained is a better solution, but I am afraid I will not be able to devote that much time to that at this time. 

Here is another modification (see the recent update to the code):
The search is much more limited now. in the worst case there will only be a few number of files to be parsed by clang, because only:
1- same named files in the same folder with the header,
2- files named after the container (namespace, class, struct, etc..) of the method/destructor/constructor/ on which the cursor is; are searched for.

This will work for the following case which is very common (Assuming that the GoTo Implementation is called on a method/constructor/destructor of ClassA defined in headerA.h and implemented in ClassA.cpp):

> proj_dir
> 
> > include_dir
> > 
> > > headerA.h
> > 
> > source_dir
> > 
> > > headerA.cpp
> > > ClassA.cpp
> > > ClassB.cpp

Additionally, this will also work if a general method (i.e. an operator that works on ClassA, is defined in 'headerA' namespace, defined in headerA.h and implemented in headerA.cpp)

**Comment by quarnster** [comment]
As long as there's an os.walk blocking the main thread, I won't accept the pull request.

**Comment by meyumer** [comment]
I removed the folder search. That part remains unchanged. 

Only fix included here is the extension to ctor/dtor implementations.

We can close this pull request with this, I might look into the threading issue if I can spare some time later.

**Comment by quarnster** [comment]
The thread based os.walk scanning has now been implemented. It seemed to work fairly well from my limited testing.

**Comment by meyumer** [comment]
nice!

I am going to report back if I see any issues.

**Comment by quarnster** [comment]
I messed up and the walk was actually done in the main thread. This has now been fixed. I also added in the regexp pre pass for finding the implementation (or fail to find it) much quicker.

**Pull request merged**
