### PR TITLE
Fix for plugin loading on ST3 + Windows

### PR DESCRIPTION
**Pull request by rchl**
In ST3, the script path is of the included module, in ST2 (Python2?) the path
is relative to the includee. Make the loading logic more flexible by looking
up 3 directories up from the current one, looking for the plugin.

### CODE REVIEW

**Comment by quarnster** [comment]
Cheers!

**Comment by rchl** [comment]
Thanks.

BTW. Do you plan to trigger update for PackageControl anytime soon? Seems like it's getting version from last year still (not that there is anything wrong with it when it comes to ST2).

**Comment by quarnster** [comment]
I don't intend to make another binary release.

**Comment by moonfruit** [comment]
Can you tell me how to build SublimeClang on Windows?
Which compiler?  What dependence?

**Comment by kblomqvist** [comment]
I would like to know this as well. I think it's only the clang dll files have to be put in place.

**Comment by quarnster** [comment]
I think I just used the standard ms sdk, or possibly the free version of visual studio. Whatever enables the "setenv" command in the command prompt. Then (written from memory):

```
setenv /x86 /release
cd *sublimeclang path*\src
mkdir build
cd build
cmake -G "NMake Makefiles" ..
nmake
```

**Comment by quarnster** [comment]
BTW, IIRC mingw32 works also, but not mingw64.

**Comment by rchl** [comment]
I've managed to compile it using VS2012 Express before.

I've generated the project files using:
  cmake -G "Visual Studio 11" (or cmake -G "Visual Studio 11 Win64" for 64-bit project).
I believe that was it at least, I don't remember now - maybe I've also added -DWIN_RELEASE.

One thing to keep in mind, you have to generate project from the Command Prompt shortcut added by VS installation (or SDK). Otherwise dumpbin won't be available in the path and you'll get some cryptic error during project generation.

But I'm not sure if there is advantage to building it yourself as libraries available at https://github.com/quarnster/SublimeClang/downloads seems to be good enough (not the latest clang but I'm not sure if latest gives any noticeable improvements on Windows).
(I wonder why link to downloads is not really advertised anywhere - are you being cautious when it comes to legal matters quarnster? Would it be OK to submit pull request with updated README that mentions it.)?

**Comment by quarnster** [comment]
Downloads used to exist as a link right next to "Code, Network, Pull requests...", but [github removed](https://github.com/blog/1302-goodbye-uploads) it a couple of months back.

I wouldn't accept a pull request pointing to the github downloads as it'll go away for real eventually, but feel free to submit a pull request pointing at http://sourceforge.net/projects/sublimeclang/files/, which is where package control should install from.

**Pull request merged**
