### PR TITLE
Bug fix: expand for ${project_path}

### PR DESCRIPTION
**Pull request by moonfruit**
when there is no .sublime-porject file in windoes folders,
program throw a excption on line 162

### CODE REVIEW

**Comment by quarnster** [comment]
If there is no .sublime-project file, ${project_path} shouldn't be used. Also binary files will not be accepted.

**Comment by moonfruit** [comment]
I DO NOT use ${project_path}!!!!
It ALSO Throw a exception on line 162!!!
Variable "project_path" is None, so "project_path.replace" throw a exception
<<<<AttributeError: 'NoneType' object has no attribute 'replace'>>>>>
Do you TEST IT ???

**Comment by moonfruit** [comment]
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by moonfruit** [comment]
binary files is my fault, I add pull request first, after it I commit binary files.
I do not know, it affect the pull request.

**Comment by quarnster** [comment]
Sorry, no I haven't used this project in a long time. 6823e7f should fix this.

**Pull request closed without merging**
